FROM python:3.9-alpine

RUN pip install sqlite-web

EXPOSE 8080

# Require authentication via SQLITE_WEB_PASSWORD environment variable
CMD ["sqlite_web", "-x", "--password", "-H", "0.0.0.0", "/data/congress-trade/db.sqlite"]
