// Re-exports from @jaywedgeworth22/congress-trading-shared with local aliases
// for backward compatibility. Prefer importing from the shared package directly
// in new code.

export {
  // Types
  type CongressTransaction,
  type TransactionsPage,
  type TransactionsQuery,
  type SecurityRef,
  type PriceClose,
  type PriceSeries,
  type BundleResponse,
  type FundamentalRow,
  type AnalystRow,
  type InsiderRow,
  type ShortVolumeRow,
  type TickerLeader,
  type ClusterBuy,
  type MemberLeader,
  type MemberPerformance,
  type ConvictionTicker,
  type BacktestHorizon,
  type TickerBacktest,
  type CommitteeConflict,
  type SharePayload,
  type CongressEvent,
  type CongressEventType,
  type Chamber,
  type PartyBucket,
  type Owner,
  type TxType,
  type MktCapBucket,
  type SnapshotManifest,
  type SnapshotTableInfo,
  // Schemas
  CongressTransactionSchema,
  TransactionsPageSchema,
  SecurityRefSchema,
  PriceCloseSchema,
  SharePayloadSchema,
  CongressEventSchema,
  ConvictionTickerSchema,
  parseArray,
  parseSafe,
  // Constants
  TICKER_ALIASES,
  MKT_CAP_THRESHOLDS,
  API_PATHS,
  WINDOW_PRESETS,
  LAG_BUCKETS,
  DEFAULT_CONGRESS_TRADE_BASE_URL,
  DEFAULT_TRANSACTIONS_LIMIT,
  MAX_REFS_BATCH,
  APP_B_ORIGIN_TAG,
  // Utils
  normalizeTicker,
  resolveTickerAlias,
  marketCapBucket,
  bracketMidpoint,
  isIsoDate,
  daysBetween,
  mergeRefs,
} from "@jaywedgeworth22/congress-trading-shared";
