name: Auto Update PRs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ${{ github.event.repository.private && fromJSON('["self-hosted", "oracle-ci"]') || 'ubuntu-latest' }}
    timeout-minutes: 15
    steps:
      - name: Automatically update PRs
        uses: chinthakagodawita/autoupdate@0707656cd062a3b0cf8fa9b2cda1d1404d74437e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: "false"
          PR_FILTER: "auto_merge"
          EXCLUDED_LABELS: "do-not-update"
          MERGE_MSG: "chore: auto-update branch with main"
          RETRY_COUNT: "3"
          RETRY_SLEEP: "2000"
          MERGE_CONFLICT_ACTION: "ignore"
