name: Debug
on: [workflow_dispatch]
jobs:
  debug:
    runs-on: [self-hosted, oracle-ci]
    steps:
      - run: sudo ss -tlnp || true
      - run: cat /etc/cloudflared/config.yml || true
      - run: docker ps -a
