name: Debug
on: [workflow_dispatch]
jobs:
  debug:
    runs-on: ${{ github.event.repository.private && fromJSON('["self-hosted", "oracle-ci"]') || 'ubuntu-latest' }}
    steps:
      - run: docker logs congress-app --tail 200
      - run: docker logs congress-sqlite-web --tail 200
