name: Deploy Deno

on:
  push:
    branches:
      - main
    paths:
      - 'app/src/**'
      - 'app/deno.json'
      - 'app/package.json'
      - 'app/package-lock.json'
  schedule:
    - cron: '0 * * * *' # Run once an hour
  workflow_dispatch:

concurrency:
  group: deploy-deno
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
        with:
          deno-version: v2.x

      - name: Install Dependencies
        working-directory: ./app
        run: deno install

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@7bded90d0d09cd99bbfb513966146315db97618b
        with:
          project: congress-trade # <-- CHANGE THIS IF YOUR DENO PROJECT NAME IS DIFFERENT
          entrypoint: src/deno/main.ts
          root: app
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_ORG_TOKEN }}
